version: '3'
services:
  app:
    image: yeahscience-app:latest
    volumes:
      - app_data:/app/rss
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FEED_URLS=${FEED_URLS}
      - BATCH_SIZE=${BATCH_SIZE}

  nginx:
    image: yeahscience-web-server:latest
    ports:
      - "80:8080"
    volumes:
      - app_data:/app/rss

volumes:
  app_data:
